import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/Provider";
import { Footer } from "@/component/footer";
import HeaderSection from "@/component/Header";
import Seo from "@/component/common/Seo";
import Analytics from "@/component/common/Analytics";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UECampus",
  description: "Generated by UECampus",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Organization and WebSite JSON-LD for structured data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "UECampus",
              url: "https://www.uecampus.com",
              logo: "https://www.uecampus.com/wp-content/uploads/2024/01/uecampus-logo.png",
              contactPoint: [
                {
                  "@type": "ContactPoint",
                  telephone: "+1-800-555-1234",
                  contactType: "customer service",
                  areaServed: "Worldwide",
                },
              ],
              sameAs: [
                "https://www.facebook.com/uecampus",
                "https://twitter.com/uecampus",
                "https://www.linkedin.com/company/uecampus",
              ],
            }),
          }}
        />

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              name: "UECampus",
              url: "https://www.uecampus.com",
              potentialAction: {
                "@type": "SearchAction",
                target: "https://www.uecampus.com/search?q={search_term_string}",
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />
        {/* Preload likely above-the-fold images so they are discoverable by the browser
            and fetched with high priority. These are conservative picks used across
            the homepage and hero/feature cards. Adjust or remove as needed. */}
        <link
          rel="preload"
          href="https://newwebsite.uecampus.com/wp-content/themes/uecampus-theme-2025/assets/images/grid-line-2.png"
          as="image"
        />
        <link
          rel="preload"
          href="https://newwebsite.uecampus.com/wp-content/themes/uecampus-theme-2025/assets/images/grid-line-3.png"
          as="image"
        />
        <link
          rel="preload"
          href="https://newwebsite.uecampus.com/wp-content/uploads/2025/08/19.jpg"
          as="image"
        />
        {/* Preload hero poster fallback used by the client hero component so it is
            discoverable as the LCP candidate and fetched with high priority. */}
        <link rel="preload" href="/assets/featured-course-thumbnail.jpg" as="image" fetchPriority="high" />
      </head>
      {/* Resource hints to shorten connection setup and reduce critical chain latency */}
      <link rel="dns-prefetch" href="https://newwebsite.uecampus.com" />
      <link rel="preconnect" href="https://newwebsite.uecampus.com" crossOrigin="anonymous" />
      <link rel="dns-prefetch" href="https://www.uecampus.com" />
      <link rel="preconnect" href="https://www.uecampus.com" crossOrigin="anonymous" />
      <link rel="dns-prefetch" href="https://new.uecampus.com" />
      <link rel="preconnect" href="https://new.uecampus.com" crossOrigin="anonymous" />
      <link rel="dns-prefetch" href="https://i.ytimg.com" />
      <link rel="preconnect" href="https://i.ytimg.com" crossOrigin="anonymous" />
      {/* Make non-critical Next.js generated CSS non-blocking by deferring it.
          This script sets Next's chunked stylesheet links (/_next/static/css/) to
          media="print" and swaps them back to "all" onload so they load
          asynchronously and don't block the initial render. */}
      <script
        dangerouslySetInnerHTML={{
          __html: `(function(){try{var ls=document.querySelectorAll('link[rel="stylesheet"][href*="/_next/static/css/"]');for(var i=0;i<ls.length;i++){var l=ls[i];if(l.dataset.deferred)continue;l.dataset.deferred='true';l.media='print';l.onload=function(){this.media='all'};} }catch(e){} })();`,
        }}
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Small, non-visual eager image to ensure discovery by LCP heuristics.
            Kept offscreen rather than display:none so browsers fetch it. */}
        <img
          src="https://newwebsite.uecampus.com/wp-content/uploads/2025/08/19.jpg"
          alt=""
          aria-hidden="true"
          loading="eager"
          fetchPriority="high"
          style={{ position: "absolute", width: 1, height: 1, left: -9999 }}
        />
        <ReduxProvider>
          <Analytics />
          <Seo />
          {/* ✅ Fixed Header */}
          
            <HeaderSection />
       

          {/* ✅ Main Content with top padding to prevent overlap */}
          <main className="pt-[80px]">
            {children}
          </main>

          {/* ✅ Normal Footer (not fixed) */}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
