import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/Provider";
import { Footer } from "@/component/footer";
import HeaderSection from "@/component/Header";
import Seo from "@/component/common/Seo";
import Analytics from "@/component/common/Analytics";
import Image from "next/image";
import logo from "../../public/assets/uecampus-logo.webp";
 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  // disable preload to avoid blocking LCP image — font will load with `font-display: swap`
  preload: false,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "UECampus",
  description: "Generated by UECampus",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Only valid head elements here */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "UECampus",
              url: "https://www.uecampus.com",
              logo: "https://www.uecampus.com/wp-content/uploads/2024/01/uecampus-logo.webp",
              contactPoint: [
                {
                  "@type": "ContactPoint",
                  telephone: "+1-800-555-1234",
                  contactType: "customer service",
                  areaServed: "Worldwide",
                },
              ],
              sameAs: [
                "https://www.facebook.com/uecampus",
                "https://twitter.com/uecampus",
                "https://www.linkedin.com/company/uecampus",
              ],
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              name: "UECampus",
              url: "https://www.uecampus.com",
              potentialAction: {
                "@type": "SearchAction",
                target: "https://www.uecampus.com/search?q={search_term_string}",
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />
        <link
          rel="preload"
          href="https://newwebsite.uecampus.com/wp-content/themes/uecampus-theme-2025/assets/images/grid-line-2.webp"
          as="image"
        />
        <link
          rel="preload"
          href="https://newwebsite.uecampus.com/wp-content/themes/uecampus-theme-2025/assets/images/grid-line-3.webp"
          as="image"
        />
        <link
          rel="preload"
          href="https://newwebsite.uecampus.com/wp-content/uploads/2025/08/19.webp"
          as="image"
        />
        <link rel="preload" href="/featured-course-thumbnail.webp" as="image" fetchPriority="high" />
        <link rel="dns-prefetch" href="https://newwebsite.uecampus.com" />
        <link rel="preconnect" href="https://newwebsite.uecampus.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://www.uecampus.com" />
        <link rel="preconnect" href="https://www.uecampus.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://new.uecampus.com" />
        <link rel="preconnect" href="https://new.uecampus.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://i.ytimg.com" />
        <link rel="preconnect" href="https://i.ytimg.com" crossOrigin="anonymous" />
        {/* Deferred stylesheet handling moved to `app/head.tsx` so it runs before Next inserts CSS links. */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Logo image moved here for valid HTML */}
        <Image
          src={logo}
          alt="UECampus Logo"
          width={150}
          height={50}
          priority
        />
        <ReduxProvider>
          <Analytics />
          <Seo />
          <HeaderSection />
          <main className="pt-[80px]">
            {children}
          </main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
